baseurl: 
timezone: Europe/Istanbul
destination: _build
exclude: ['README.md', '.sass-cache']
include: [.htaccess]
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
sass:
  style: compressed
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Berkan Dirim"
            categories: "conferenece"
            layout: "post"
            comments: true
gems:
    - jekyll-sitemap