url: http://www.dirim.co
baseurl:
timezone: Europe/Istanbul
destination: _build
exclude: ['README.md', '.sass-cache', 'bower_components']
include: ['.htaccess', 'fonts']
highlighter: rouge
pygments_options: ['lineanchors']
permalink: /blog/:year-:month-:day/:title/
sass:
  style: compressed
gems:
    - jekyll-sitemap